# Generated by Django 3.0.4 on 2020-03-22 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Generator',
            fields=[
                ('id', models.CharField(max_length=252, primary_key=True, serialize=False, unique=True)),
                ('data', models.TextField()),
            ],
            options={
                'verbose_name': 'Generator',
                'verbose_name_plural': 'Generators',
            },
        ),
        migrations.CreateModel(
            name='GeneratorToCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranshigen.Category')),
                ('generator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranshigen.Generator')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='generators',
            field=models.ManyToManyField(related_name='category', through='ranshigen.GeneratorToCategory', to='ranshigen.Generator'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ranshigen.Category'),
        ),
    ]
