# Generated by Django 3.0.4 on 2020-03-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranshigen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generator',
            fields=[
                ('id', models.CharField(max_length=252, primary_key=True, serialize=False, unique=True)),
                ('data', models.TextField()),
            ],
            options={
                'verbose_name': 'Generator',
                'verbose_name_plural': 'Generators',
            },
        ),
    ]
