# Generated by Django 3.0.4 on 2020-03-17 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ranshigen', '0002_generator'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratorToCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranshigen.Category')),
                ('generator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranshigen.Generator')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='generators',
            field=models.ManyToManyField(related_name='category', through='ranshigen.GeneratorToCategory', to='ranshigen.Generator'),
        ),
    ]
