# Generated by Django 3.0.4 on 2020-03-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('ranshigen', '0004_category_image'), ('ranshigen', '0005_auto_20200322_1918'), ('ranshigen', '0006_auto_20200322_1920')]

    dependencies = [
        ('ranshigen', '0003_auto_20200317_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='categories'),
        ),
    ]
